version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:ecommerce
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db 
  db:
    image: postgres
    container_name: postgres_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=new
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2000
    ports:
      - "5432:5432"
    networks:
      app_net:
        ipv4_address: 192.168.0.2
    
